### ISSUE TITLE
colab NameError: str2optimizer8bit_blockwise is not defined

### ISSUE THREAD

**Issue by kimtaehyeong** [camenduru/stable-diffusion-dreambooth-colab#3]
hello.

Based on what you suggested, I ran it in Colab.
However, the following error occurred.
how can i solve it ?
->
```NameError: name 'str2optimizer8bit_blockwise' is not defined```

thank you for the nice project

**Comment by camenduru** [comment]
please try again

**Comment by kimtaehyeong** [comment]
Thank you.
I was able to fix the problem.
